### ISSUE TITLE
Reality check messages and re-direct behaviour in ComeOns new mobile site

### ISSUE THREAD

**Issue by rebecka01** [nolimitcity/nolimit.js#1]
Might be that comeon needs more help with the implementation? 
@kribblo has Sefa talked to you and asked for help? Or my real question is if you know if they are ready (maybe Sefa has talked to you and you have a feeling if this is under control).

Mail from Jenny Rudell today:
"Hi everyone,
 
I tested this today and the second step is removed so much better. Some issues observed:
 
1. On Creepy Carnival the reality check message showing in the game is in English. In Space Arcade it’s in Finnish.
2. After clicking on the reality check message inside Creepy Carnival and being directed back to the site I get a red error message at the top of the screen saying something like “an error occurred while playing the game”
3. After getting that red error message, it’s not possible to scroll the page anymore (guessing this is on our side).
 
Is the problem in point 2 because of something on our side (doesn’t behave like this with any other game providers), or is it because of what happens on NLC side when clicking on the responsible gaming error message inside the game? What does that action trigger in the background?
 
Cheers
Jenny"

**Comment by kribblo** [comment]
This issue was moved to nolimitcity/creepycarnival#41
