### ISSUE TITLE
Unsafe accessing of 'src' property

### ISSUE THREAD

**Issue by Altolias** [nolimitcity/nolimit.js#14]
I'm having an issue running tests because of this line: 
https://github.com/nolimitcity/nolimit.js/blob/cd93f7bc24e2808ffccd1c6aa2973360702a7e69/src/log-handler.js#L20
While running tests the tag variable will be undefined and trying to access the 'src' property of it will cause the tests on components that have this library imported to fail.

Consider making accessing this property safe by adding a undefined check before.

**Comment by kribblo** [comment]
@Altolias  What kind of tests are we talking about here? The proper solution would be to not log anything during tests, so what are you running and how?

**Comment by Altolias** [comment]
I have set up a repository to reproduce this here: https://github.com/Altolias/fail-test

I am using jest for testing. These tests run fine on version 1.2.4 but fail on 1.2.42.
The tests themselves have nothing to do with nolimit itself but if the component that is being tested accesses nolimit in any way then the whole test suite fails for that component.

**Comment by kribblo** [comment]
Yes, what I am saying is that the proper way to address this is probably an option to disable logging altogether, because we do not want to log automated tests anyway. We were not aware that tests were running in this way. The bug is not in question, it's just that this is not what it was designed for.

**Comment by Altolias** [comment]
The option to disable logging would not help in this case because the error happens before init or load is called

**Comment by Altolias** [comment]
A solution would also not to log anything while just instantiating this library but only after something is called and adding an option to disable logging altogether or even adding a possibility to provide your own implementation for logging.

**Comment by grunka** [comment]
Added some catch-all error handling to that part which will disable logging in case of that check failing
