### ISSUE TITLE
Allow attribute will take precedence over 'allowfullscreen'.

### ISSUE THREAD

**Issue by jonaswalekvist** [nolimitcity/nolimit.js#15]
![image](https://user-images.githubusercontent.com/20856951/71966468-f2516c80-3201-11ea-9e22-02d3b00c7e7b.png)

Maybe a simple solution:
https://stackoverflow.com/questions/57665508/how-to-resolve-allow-attribute-will-take-precedence-over-allowfullscreen-warni

**Comment by grunka** [comment]
I think this might have been solved at some point somehow since this issue was created?
