### ISSUE TITLE
Update examples in documentation with newer games (now it is CreepyCarnival and SpaceArcade)

### ISSUE THREAD

**Issue by rebecka01** [nolimitcity/nolimit.js#16]
Now we have 'CreepyCarnival' (that doesn't exist any more in all environments) and 'SpaceArcade' (that is not certified for the new jurisdiction, and also we might remove it soon since we don't update it).

Thing is I think they use the example since we now and then get from new integrations that game is not working and it is because they are trying with CreepyCarnival.

So would be great with newer games

![Screenshot 2020-01-15 at 08 02 04](https://user-images.githubusercontent.com/15359567/72412681-38f91680-376e-11ea-9052-36ab69b76785.png)

**Comment by rebecka01** [comment]
Maybe we could use DragonTribe in the examples - that is a nice looking game :)

**Comment by kribblo** [comment]
Changed to DragonTribe or Wixx, can update further, but Wixx seems to do fine still

**Comment by rebecka01** [comment]
looked in the nolimit.js doc and there it was updated ok
