### ISSUE TITLE
Add comment to documentation that 'device' should be sent in. Update comment also for jurisdiction?

### ISSUE THREAD

**Issue by rebecka01** [nolimitcity/nolimit.js#17]
https://nolimitjs.nolimitcdn.com/jsdoc/@nolimit/nolimit.js/latest/module-nolimit.html#.init

Can we add comments on two things?
A) device
B) jurisdiction

A) device
We have had several integrations that don't specify device since it says 'optional' (so for their players it opens desktop version on mobile). 
I heard that we can't change it to 'mandatory' (and if I recall correct, this was due to that it can stop working for customers already integrated).
But maybe we can add some comment? that they should send in 'device' that otherwise it will default to desktop version. 

B) jurisdiction
We had an incident with ATG. They stopped sending in jurisdiction since they saw that it says "optional". Saw that we already have comment here, and also since jurisdiction can be sent in via wallet and other ways we can't say that it must be sent in in order to work. So I don't know what we should write here. 
If you also can't think of anything, maybe you can ask Jonas T or Emil for suggestions?

![Screenshot 2020-03-09 at 14 48 51](https://user-images.githubusercontent.com/15359567/76221463-68ca1500-6219-11ea-8c6c-f7c2dcbb3261.png)

**Comment by kribblo** [comment]
I'll add a stronger recommendation to always set device in the docs. For jurisdiction, it is pretty well documented in the README, and the API docs point to the README for details. You have it right on the different ways it can be set. I guess if they get it wrong we might have to solve this with communication in many cases. But I can ofc make changes if someone has suggestions.

**Comment by kribblo** [comment]
`device | String | <optional> | desktop | type of device: 'desktop' or 'mobile'. Recommended to always set this to make sure the correct device is used.`

**Comment by emil-nolimitcity** [comment]
Can you please add a sentence about default like: If not set it defaults to device type desktop.

**Comment by emil-nolimitcity** [comment]
The jurisdiction parameter handling should be communicated and agreed during integration. Wording as it is now is sufficient. Device specification is also good now.
