### ISSUE TITLE
Swipe animation on landscape doesn't work and blocked game playing.

### ISSUE THREAD

**Issue by ning-nolimitcity** [nolimitcity/nolimit.js#19]
Talked to Emil about this and add an issue here to evaluate if it's a practical problem. 
'nolimit.js', '1.2.51' with `Iphone X`

How to reproduce:
1. open safari in your phone and go to the test page.
2. click the share button in the bottom of the browser, the icon is a square with an arrow pointing up.
3. in the menu, choose "Add to home screen". then you got an icon on your home screen.
4. click the new icon to enter the test page, use "mobile new page" to play the game.

Noticed the differences:
When you start the test page in Safari, with landscape mode, the height of the game is not fully displayed because of the url bar/tabs, so you can use the swipe animation to hide all the urls/tabs to play full screen.
When you start the test page with the home icon, the top url bar is always there and the game is fully displayed under it, so it's actually already in full screen mode. Then the swipe doesn't work but the swipe animation is still triggered, blocking any click of the game.

**Comment by ning-nolimitcity** [comment]
screenshot: (the spin was played in portrait mode so there is a win displaying)
![image](https://user-images.githubusercontent.com/17565912/80210812-b74e3a00-8634-11ea-8efc-3ddbfb1dfde2.png)

**Comment by rebecka01** [comment]
vinita also found issue with swipe up https://github.com/nolimitcity/nolimit-slot-launcher/issues/164

**Comment by grunka** [comment]
This is a very special case but I think its been fixed now by detecting the `navigator.standalone` mode that this is in which is a Safari-specific thing that behaves in a third fun way.

**Comment by rebecka01** [comment]
@ning-nolimitcity Can you see if it works better also for you and your device?

**Comment by ning-nolimitcity** [comment]
Now the swipe animation doesn't show in the same case.
