### ISSUE TITLE
Jurisdiction LT is missing in the documentation.

### ISSUE THREAD

**Issue by rebecka01** [nolimitcity/nolimit.js#20]
We now also have jurisdiction LT (and I think we have added this to nolimt.js), but the documentation isn't updated with this. 

So:

1. confirm that we support jur LT (I think this is added since we have tested in test env, but pls have an extra look)
2. add info in doc that we support also jurisdiction LT
3. it says "_Currently there is special behaviour in our games for jurisdictions "UKGC" (UK) and "SE"_ " and since LT also has special behaviour (autoplay is disabled), we should add LT also here. 

https://nolimitjs.nolimitcdn.com/jsdoc/@nolimit/nolimit.js/latest/index.html#jurisdictions

<img width="942" alt="Screenshot 2020-05-05 at 08 37 03" src="https://user-images.githubusercontent.com/15359567/81040445-abbc0800-8eab-11ea-8bac-160ae44ebf5d.png">

**Comment by kribblo** [comment]
Documentation updated: https://nolimitjs.nolimitcdn.com/jsdoc/@nolimit/nolimit.js/latest/#jurisdictions

Needs certain versions of the games to be updated as well.

**Comment by rebecka01** [comment]
verified ok that it is update
Saw that you also updated that DK has special behaviour in clients 👍 

Regarding clients, great that you saw that they weren't copied out! 

So seems like we only did for cert. In the QA issue there is a list of games that were included in the "cert-project" https://github.com/nolimitcity/QA/issues/151
Emil will check with Malcolm what the time plan is so we can plan a prod release of the games.
