### ISSUE TITLE
map language code pe and cl to spanish language es

### ISSUE THREAD

**Issue by emil-nolimitcity** [nolimitcity/nolimit.js#21]
There are an operator that send in country codes pe (Peru) and cl (Chile) as language codes. Can we just map these to es on load as a convenience for them?

**Comment by grunka** [comment]
Do we know which loading method they are using? Since we could do this either in nolimit.js or a game loader and if they are using a custom game loader that might be a better place to do this kind of mapping.

**Comment by emil-nolimitcity** [comment]
Hi, sorry for late reply. We are doing this for the Betsson group and they use the API to the best of my knowledge.

**Comment by grunka** [comment]
With the release of #22 this update has also been released. Available in version 1.2.66 which has also been published to npm.

**Comment by rebecka01** [comment]
tested in test via replay links, changed the lang to 'pe' and 'cl' and keypad looked like it was in Spanish (replay pop up only has 'en' and 'sv' at the moment).
https://replay-test.nolimitcity.com/show/tapeharahazu?device=desktop&language=cl&environment=test&operator=FAKE1

**Comment by rebecka01** [comment]
I slacked Malcolm

> Hi,
> Remember that you asked about mapping ‘pe’ and ‘cl’ to lang ‘es’? I think it was for Betsson. 
> That has now been fixed: https://github.com/nolimitcity/nolimit.js/issues/21 so it is out now in latest nolimit.js, 
> Betsson doesn’t use “nolimit.js latest” so they need to do update on their side. Change is available in version 1.2.66
