### ISSUE TITLE
Swedish jurisdiction links need to conform exactly to logotypes given by spelinspektionen.

### ISSUE THREAD

**Issue by emil-nolimitcity** [nolimitcity/nolimit.js#22]
If a game is loaded with the Swedish jurisdiction parameters for spelpaus spelgränser and självtest add a top div vertically above the game container in and place the buttons provided below with the same linking as done before. Then remove them from the options object so that the game does not receive them. 

https://www.spelinspektionen.se/press/nyhetsarkiv/enklare-for-spelare-att-ta-kontroll-over-sitt-spelande/

**Comment by grunka** [comment]
New bar created, "stealing" links and events that would otherwise be sent to the games to make them show the links and showing in the bar instead.
