### ISSUE TITLE
iPhone XR + Firefox, Yandex + Landscape - Swipe up animation does not work 

### ISSUE THREAD

**Issue by vinitanolimit** [nolimitcity/nolimit.js#26]
Deadwood 1.0.177 ⋅ slot-launcher 1.5.23 ⋅ slot-keypad 1.5.20 ⋅ slot-game 0.48.12 ⋅ game-api 1.0.3

**Comment by grunka** [comment]
Added detection for Firefox and Yandex to not try to do the swipe up for them

**Comment by vinitanolimit** [comment]
Now no Swipe animation is coming up in both the browsers (FF, Yandex). So marking it verified OK.

MilkyWays 1.0.63 ⋅ slot-launcher 1.5.56 ⋅ slot-keypad 1.5.28 ⋅ slot-game 0.48.27 ⋅ game-api 1.0.10
