### ISSUE TITLE
There is a gap, looks like the game is too far down. iPhone + Safari. Twin casino. Swedish Jurisdiction

### ISSUE THREAD

**Issue by rebecka01** [nolimitcity/nolimit.js#28]
Twincasino goes via Gig. 
They get jur = SE via that country is Sweden (i.e. they don't send jurisdiction via game launcher)

I don't know if it is us or the customer that creates this "gap".
See screen shot. 
It looks like the game has fallen down a bit, and there is a gap. 
twix.com
iPhone XR + safari

You need to log in to get this. I got to borrow an account from them. Let me know and I'll give you the credentials. 

![IMG-4527](https://user-images.githubusercontent.com/15359567/90029341-0f2fb000-dcbb-11ea-980d-be7a7ba9712b.PNG)

**Comment by grunka** [comment]
I've taken a quick look and we cover the complete area that we are given to show the game in. And that area is the same as the area that gig gives us. The gap seems to be on the twin.com page, but it is a bit special and confuses the inspector tools so I can't really say where it is added.

**Comment by rebecka01** [comment]
@grunka 
Thanks for looking!

I've sent them a message. 
Hope they will have a look and that they can fix. 

I'll close this now
