### ISSUE TITLE
Add Germany as a jurisdiction parameter

### ISSUE THREAD

**Issue by emil-nolimitcity** [nolimitcity/nolimit.js#29]
Use DE for the german jurisdiction parameter.

**Comment by rebecka01** [comment]
I think it is high time to get this fixed now. 
https://nolimitjs.nolimitcdn.com/jsdoc/@nolimit/nolimit.js/latest/index.html

<img width="1062" alt="Screenshot 2020-09-30 at 13 35 20" src="https://user-images.githubusercontent.com/15359567/94680359-ed00f880-0321-11eb-8e32-7cef77e61d42.png">

**Comment by kribblo** [comment]
https://nolimitjs.nolimitcdn.com/jsdoc/@nolimit/nolimit.js/latest/#jurisdictions should be updated by now

**Comment by rebecka01** [comment]
docs have DE added, and if you select 'Germany' on the test operator page when you launch the game you get jur = DE. 
so verified ok.

Just some thoughts:
More has happend on the jurisdiction side, but I think we need to take a full grip. 
What we want to add and how much info. Guessing we should either remove what features the different jursidiction has for all, all add it for all. We support more than is in the docs today. But now DE is in the docs and that was what this ticket was about :)
