### ISSUE TITLE
Update documentation regarding jurisdictions. 

### ISSUE THREAD

**Issue by rebecka01** [nolimitcity/nolimit.js#30]
https://nolimitjs.nolimitcdn.com/jsdoc/@nolimit/nolimit.js/latest/index.html

a)
> Our supported jurisdictions: "DE", "DK", "LV", "RO", "SE", "UKGC", "MT", "LT", "ES", "PT", "IT"

Update this part to reflect what jurisdictions we support. Ask Emil or Paul on what jurisdictions we support if you don't know.
(Or is it possible to automatically update when we add new jurisdictions?) 
Pls note: Don't add NorskTipping here in the docs, that was an internal solution for us.

b)
> Currently there is special behaviour in our games for jurisdictions "DK", "LT", "UKGC" (UK) and "SE" (Lotteriinspektionen, Sweden).
> UKGC, LT, DK, DE
> 
> No extra configuration needed.

I think we can remove this part. Or update so all jurisdictions with 'special behaviour' are added, but then we need to keep it updated.

**Screen shot on how it looks today:**

![Screenshot 2020-10-13 at 08 34 24](https://user-images.githubusercontent.com/15359567/95824493-ace14300-0d2f-11eb-8a3e-3492ab0a6a65.png)

**Comment by grunka** [comment]
Texts have been updated, will go out in next publish

**Comment by rebecka01** [comment]
Verified ok
a) Now we changed the text so that specified jurisdictions are examples and that person developing should contact us, this so that we don't need to maintain. 
b) was removed

![Skärmavbild 2020-11-11 kl  10 52 28](https://user-images.githubusercontent.com/15359567/98797040-59384700-240c-11eb-9b4f-b7c15d093ee5.png)
