### ISSUE TITLE
Add +18 Next to Swedish jurisdiction buttons 

### ISSUE THREAD

**Issue by emil-nolimitcity** [nolimitcity/nolimit.js#31]
Just add a text x18 next to the buttons with a font we always have available in similar size to text on the buttons.

**Comment by grunka** [comment]
Has been added will go out on next publish

**Comment by rebecka01** [comment]
Should we always get it? I only got it when I opened with mobile (iframe), when I used mobile (new page) it wasn't there.  
The "+18" and game name overlapped a bit - should/can do anything different. 

Screen shots are from iPhone XR and Safari. 

**mobile (new page), missing "+18"**
![34899](https://user-images.githubusercontent.com/15359567/98509750-0de23500-2262-11eb-84e8-5bacebfd28cf.jpg)

**mobile (iframe), "+18" is there**

![48492](https://user-images.githubusercontent.com/15359567/98509757-120e5280-2262-11eb-962b-b143ddc83769.jpg)

**Comment by grunka** [comment]
The new page loading uses the latest nolimit.js from production (and due to how it works it has to) which does not have the fixes pushed yet. So I'll close this again with that information

**Comment by vinitanolimit** [comment]
Verified Ok - MilkyWays 1.0.63 ⋅ slot-launcher 1.5.56 ⋅ slot-keypad 1.5.28 ⋅ slot-game 0.48.27 ⋅ game-api 1.0.10
