### ISSUE TITLE
Swip up doesn't work on my phone. iPhone XR + Safari, iOS 14.2

### ISSUE THREAD

**Issue by rebecka01** [nolimitcity/nolimit.js#32]
Swip up doesn't work on my phone. iPhone XR + Safari, iOS 14.2.
I have the finger animation that I should swip up - but noting happens, I can't go full screen. I'll attach screen shot.

Jaiveer had 14.1 and it worked, then he updated to 14.2 and it stopped working. 
Strange thing is that Emil has also 14.2, but it works for him. 

I compared with Emil and for me the back ground of the game doesn't go out to the sides (see screen shot), it does for him.

Me: iPhone XR + Safari, iOS 14.2 - Doesn't work
Emil: iPhoneX + Safari, iOS 14.2. OK
Jaiveer: iPhone 8, iOS 14.2 - doesn't work
Jaiveer: iPhone 8, iOS 14.1 - ok
Priya: iPhone X, iOS 14.0.1 - ok
Twinkle: iPhone6s safari ios 14.0.1 - ok

![95101](https://user-images.githubusercontent.com/15359567/99675537-9f7a4f80-2a77-11eb-9081-64576d1f91e8.jpg)

**Comment by rebecka01** [comment]
now also customers has found this https://nolimitcity.jitbit.com/helpdesk/Ticket/33199756

**Comment by emil-nolimitcity** [comment]
Remove it completely.

**Comment by grunka** [comment]
Has been removed in version 1.2.73 of nolimit.js

**Comment by rebecka01** [comment]
tested with my phone in test and no swip up 👍

**Comment by rebecka01** [comment]
out in prod and James is updated so he can update customer
