### ISSUE TITLE
Add hideExitButton attribute to the game launch parameters. 

### ISSUE THREAD

**Issue by emil-nolimitcity** [nolimitcity/nolimit.js#34]
There are operators that want to control closing of mobile games from outside of our game area so we need to support the removal of the home button in the mobile interface.

A new options attribute should be added hideExitButton.

**Comment by nlc-sorabh** [comment]
Added the hideExitButton in our game-loader.html file. And tested it via below link:
`https://test.nolimitcdn.com/loader/game-loader.html?device=desktop&language=en&operator=FAKE1&game=Deadwood&hideExitButton=true`

**Comment by rebecka01** [comment]
verified ok in test
