### ISSUE TITLE
Header x-country is no longer allowed to be fetched

### ISSUE THREAD

**Issue by grunka** [nolimitcity/nolimit.js#40]
... so will remove code that attempts to do so

**Comment by rebecka01** [comment]
![Screenshot 2022-05-09 at 10 35 14](https://user-images.githubusercontent.com/15359567/167378401-83f2d64b-38a8-48cc-ad26-963f4f814ddd.png)

**Comment by grunka** [comment]
Done

**Comment by rebecka01** [comment]
verified ok
