### ISSUE TITLE
FR: Add game client version override. 

### ISSUE THREAD

**Issue by jonaswalekvist** [nolimitcity/nolimit.js#7]
I would like a way to load a which ever version of the game client o the fake operator site. At the moment it will load the latest successful built version. But it would be awesome to be able to override this to load older versions, so we can compare different this. 

This was briefly discussed with @grunka

**Comment by kribblo** [comment]
Reasonable request, this functionality was removed in nolimit.js but can be restored and added to test pages.

**Comment by kribblo** [comment]
Added back loading by version to nolimit.js, needs interface in tester page too.

**Comment by kribblo** [comment]
Added
