### ISSUE TITLE
Log failures on client side

### ISSUE THREAD

**Issue by tegman** [nolimitcity/nolimit.js#9]
I suspect we have some issues on the client side, games doesn't always load. Maybe connected to some asynch shit loaded in wrong order? I've seen it in test, and in prod. Seems to be worse in prod with worse connection

Can we implement a client side log, that sends basic fail info to a cloud db. one table with data below. 

Something like:
start time, failure time, env, client (operator), user(?), ip, ip-country, process checkpoint id (how far did it work), game, channel, browser, os, language, fail code, fail message

Watch out for recursive messages, we don't want to loop this.  Max one attempt!

**Comment by kribblo** [comment]
Example request from @bucht 
```
curl -X POST -d '{"key": "fbac5670-6f2d-42ad-9c65-b77a64dd9789","body": {"time": "2019-06-20 12:37:00", "event": "GAME_LOADED", "game": "Tombstone", "token": "token2", "device": "iphone", "data": {"test": "testar", "test2": "testar2"}}}' https://gamelog.nolimitcity.com/prod
```
Initial columns:

![image](https://user-images.githubusercontent.com/861819/65420741-390d8900-de02-11e9-8bc4-5cdebe0f6dd7.png)

**Comment by kribblo** [comment]
Debug help for CURL: https://stackoverflow.com/questions/12173990/how-can-you-debug-a-cors-request-with-curl

**Comment by kribblo** [comment]
We have some of these things working now in test/partner. For logging Websocket problems, games need a fresh slot-api, but regular errors are being logged. Need more work for more details + logging more cases, traces etc, but all the basics are in place and can for the most part be added as we go along. Need some Athena support from @bucht to see how we can extract useful stuff from this.

**Comment by emil-nolimitcity** [comment]
Add a filter on at the client so we just send the first error and not bombard the server with consecutive errors that are more or less the same origin as the initial error.
